config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'guide/index'
  get 'guide/dashboard'
  get 'guide/register'

  resources :courses
  resources :professors
  resources :users

  root 'guide#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
    #validates_presence_of :abbrev, :name, :crn, :teacher
    validates :abbrev,  presence: true, format: { with: /CS+\s+\d{3}/, message: "must have the format 'CS XYZ' where XYZ is the three-digit course number" }, uniqueness: {message: " already exists"}
    validates :name,  presence: true, uniqueness: true
    validates :crn,  presence: true, length: { is: 6, wrong_length: " must be 6 digits long" }, uniqueness: true
end

app/models/professor.rb
class Professor < ActiveRecord::Base
    #validates_presence_of :name, :office, :classes
    validates :name,  presence: true, uniqueness: {message: " already exists"}
    validates :office,  presence: true
    validates :classes, allow_blank: true, format: { with: /CS+\s+\d{3}/, message: "must have the format 'CS XYZ' where XYZ is the three-digit course number" }
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.emailID = emailID} #Sorry I might have messed this line up :(
    validates :username,  presence: true, length: { maximum: 15 }, uniqueness: true
    validates :password,  presence: true, length: { maximum: 15 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :emailID, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    
  def show
    @course = Course.find params[:id]
    #redirect_to courses_path
  end
   
  def index
    @courses = Course.all
  end
    
  def new
    #render new template
  end
    
  def create
    vals = params[:course]
    # if(Course.exists?(:abbrev => vals[:abbrev]))
    #   flash[:warning] = "#{vals[:abbrev]} already exists! Please try a new one."
    # else
    @course = Course.create(params.require(:course).permit(:abbrev, :name, :crn, :teacher))
    if @course.errors.any?
        flash[:warning] = @course.errors.full_messages.first
        redirect_to :back
    else
        redirect_to courses_path
    end
      #end
    #     if !@course.valid?
    #         flash[:warning] = "Invalid Course Entry."
    #     end
    # end
    # @course = Course.create!(params.require(:course).permit(:abbrev, :name, :crn, :teacher))
    # flash[:notice] = "#{@course.abbrev} was successfully created."
    #redirect_to courses_path
  end
    
  def edit
    @course = Course.find params[:id]
  end
    
  def update
    vals = params[:course]
    @course = Course.find params[:id]
    @course.update_attributes(params.require(:course).permit(:abbrev, :name, :crn, :teacher))
   # @err = @course.errors
    if @course.errors.any?
        flash[:warning] = @course.errors.full_messages.first
        redirect_to :back
    else
        flash[:notice] = "#{@course.abbrev} was successfully updated"
        redirect_to courses_path
    end
    # if(Course.exists?(:abbrev => vals[:abbrev]) and @course.abbrev != vals[:abbrev])
    #   flash[:warning] = "#{vals[:abbrev]} already exists! Please try a new one."
    # else
    #   @course.update_attributes!(params.require(:course).permit(:abbrev, :name, :crn, :teacher))
    #   flash[:notice] = "#{@course.abbrev} was successfully updated." 
    # end
    #redirect_to course_path(@course)
  end

  def destroy
    @course = Course.find params[:id]
    @course.destroy
    flash[:notice] = "Course '#{@course.abbrev}' deleted."
    redirect_to courses_path
  end
  
end

app/controllers/guide_controller.rb
class GuideController < ApplicationController
  def index
  end
  def dashboard
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController

    def show
        @professor = Professor.find params[:id]
        #redirect_to professor_path
    end
    
    def index
        @professors = Professor.all
    end
    
    def new
        #render new template
    end
    
    def create
        vals = params[:professor]
        # if(Professor.exists?(:name => vals[:name]))
        #   flash[:warning] = "#{vals[:name]} already exists! Please try a new one."
        # else
        @professor = Professor.create(params.require(:professor).permit(:name, :office, :classes))
        if @professor.errors.any?
            #flash[:warning] = "Invalid Professor Entry."
            #flash[:warning] = "#{vals[:name]} already exists! Please try a new one."
            flash[:warning] = @professor.errors.full_messages.first
            #redirect_to :back
            redirect_to professors_path
        else
            flash[:notice] = "#{@professor.name} was successfully created."
            redirect_to professors_path
        end
        #     if !@professor.valid?
        #         flash[:warning] = "Invalid Professor Entry."
        #     else
        #         flash[:notice] = "#{@professor.name} was successfully created."
        #     end
        # end
        #redirect_to professors_path
    end
    
    def edit
        @professor = Professor.find params[:id]
        #redirect_to edit_professor_path
    end
    
  def update
    vals = params[:professor]
    @professor = Professor.find params[:id]
    @professor.update_attributes(params.require(:professor).permit(:name, :office, :classes))
    if @professor.errors.any?
        flash[:warning] = @professor.errors.full_messages.first
        redirect_to :back
    else
        flash[:notice] = "#{@professor.name} was successfully updated." 
        redirect_to professor_path(@professor)
    end
        
    # if(Professor.exists?(:name => vals[:name]) and @professor.name != vals[:name])
    #   flash[:warning] = "#{vals[:name]} already exists! Please try a new one."
    # else#(Course.exists?(:abbrev => vals[:classes]))
    #     @professor.update_attributes!(params.require(:professor).permit(:name, :office, :classes))
    #     flash[:notice] = "#{@professor.name} was successfully updated." 
    # #else
    #   #@professor.update_attributes!(params.require(:professor).permit(:name, :office, :classes))
    #     #flash[:notice] = "#{@professor.classes} is not a listed course." 
    # end
    # redirect_to professor_path(@professor)
  end

  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy
    flash[:notice] = "Professor '#{@professor.name}' deleted."
    redirect_to professors_path
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.create(params.require(:user).permit(:username, :password, :emailID))
    if !@user.valid?
      flash[:warning] = "Invalid Registration."
    else
      flash[:notice] = "User Successfully Registered"
    end
    redirect_to guide_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/edit.html.haml
%h1 Edit Existing Course

= form_tag course_path(@course), :method => :put do

  = label :course, :abbrev, 'Course Abbreviation'
  = text_field :course, 'abbrev'

  = label :course, :name, 'Course Name'
  = text_field :course, 'name'

  = label :course, :crn, 'CRN'
  = text_field :course, 'crn'
  
  = label :course, :teacher, 'Handling Professor'
  = text_field :course, 'teacher'

  = submit_tag 'Update Course Info'
  //  - if(!Course.where(:abbrev => @course.abbrev).empty?)
  //    = Course Abbreviation already used
  //  - else

  = link_to '<button type="button">Cancel</button>'.html_safe, courses_path

app/views/courses/index.html.haml
%h1 All Courses

%table#courses
  %thead
    %tr
      %th Course Abbrev
      %th Course Name
      %th CRN
      %th Professor
  %tbody
    - @courses.each do |course|
      %tr
        %td= link_to(course.abbrev, {:action => 'show', :id => course.id}, :class => 'action show')
        %td= course.name
        %td= course.crn
        %td= course.teacher
        



= link_to '<button type="button">Add New Course</button>'.html_safe, new_course_path
= link_to '<button type="button">Back to Dashboard</button>'.html_safe, guide_dashboard_path

app/views/courses/new.html.haml
%h1 Enter New Course

= form_tag courses_path do

  = label :course, :abbrev, 'Course Abbreviation'
  = text_field :course, 'abbrev'

  = label :course, :name, 'Course Name'
  = text_field :course, 'name'

  = label :course, :crn, 'CRN'
  = text_field :course, 'crn'
  
  = label :course, :teacher, 'Handling Professor'
  = text_field :course, 'teacher'

  = submit_tag 'Save Changes'
  = link_to '<button type="button">Back to Courses</button>'.html_safe, courses_path

app/views/courses/show.html.haml
%h2 Details about #{@course.abbrev}

%ul#details
  %li
    Course Name:
    = @course.name
  %li
    Course CRN:
    = @course.crn
  %li
    Handling Professor:
    - if(!Professor.where(:name => @course.teacher).empty?)
      = link_to(@course.teacher, {:action => 'show', :id => (Professor.where(:name => @course.teacher).ids) , :controller=>"professors"}, :class => 'action show') 
    - else
      = @course.teacher

= link_to '<button type="button">Edit</button>'.html_safe, edit_course_path(@course)
= button_to 'Delete', course_path(@course), :method => :delete, :confirm => 'Are you sure?'
= link_to '<button type="button"><< Back</button>'.html_safe, courses_path 

app/views/guide/dashboard.html.haml
!!!
%html{:lang => "en"}
  %body
    #wrapper
      / Sidebar
      #sidebar-wrapper
        %ul.sidebar-nav
          %li.sidebar-brand
            %a
              Features
          %li
            //%a{:href => "#"} Courses
            = link_to 'Courses', courses_path
          %li
            //%a{:href => "#"} Professors
            = link_to 'Professors', professors_path

          %li
            %a{:href => "#"} Feature3
          %li
            %a{:href => "#"} Feature4
          %li
            %a{:href => "#"} Feature5
          %li
            %a{:href => "#"} Feature6
          %li
            %a{:href => "#"} Feature7
      / /#sidebar-wrapper
      / Page Content
      #page-content-wrapper
        .container-fluid
          %h1 Binghamton University Guide Dashboard Help
          %p Click on toggle menu to explore features
          %p On left side you can see all features and on click of any particular feature respective page will open here.
          
          
          %button#menu-toggle.btn.btn-secondary{:formaction => "#menu-toggle", :type => "submit"} Toggle Menu
          %br
        = link_to '<button type="button" class="btn">Back to Homepage</button>'.html_safe, guide_index_path
        %br
        = link_to '<button type="button" class="btn">List of Users</button>'.html_safe, users_path
      / /#page-content-wrapper
    / /#wrapper
    / Bootstrap core JavaScript
    %script{:src => "vendor/jquery/jquery.min.js"}
    %script{:src => "vendor/bootstrap/js/bootstrap.bundle.min.js"}
    / Menu Toggle Script
    :javascript
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
      });

app/views/guide/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "/default.css", :rel => "stylesheet", :type => "text/css"}/
    %title Binghamton University Guide
  %body
    .container
      #header.span-24
        %p.heading
          Welcome to The
          = succeed "inghamton" do
            %b B
          = succeed "niversity" do
            %b U
          = succeed "uide" do
            %b G
      .span-24
        = yield
      #footer.span-24
      %fieldset
        %legend
          %h2 Log in
        %h4 Username
        %input{:name => "username", :type => "text"}
        %h4 Password
        %input{:name => "password", :type => "text"}
        %br
        %br
        = link_to '<button type="button">Sign In</button>'.html_safe, guide_dashboard_path
        %br
        %p 
          New User?
          = link_to '<button type="button">Sign Up</button>'.html_safe, guide_register_path
        %br
      %br
      %br
      = link_to '<button type="button">Sign in as Guest</button>'.html_safe, guide_dashboard_path

app/views/guide/register.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "/default.css", :rel => "stylesheet", :type => "text/css"}/
    %title Binghamton University Guide
  %body
    .container
      #header.span-24
        %h2.page_heading
          User Registration
        %p.heading
          Fill in all the details below
      .span-24
        = yield
      #footer.span-24
= form_tag users_path do

  = label :user, :emailID, 'E-Mail ID'
  = text_field :user, 'emailID'

  = label :user, :username, 'Username'
  = text_field :user, 'username'

  = label :user, :password, 'Password'
  = text_field :user, 'password'

  = submit_tag 'Register'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Binghamton University Guide
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %h1.title
      %center Binghamton University Guide
    #main
      - if flash[:notice]
        #notice.message
          = flash[:notice]
      - elsif flash[:warning]
        #warning.message
          = flash[:warning]
      = yield

app/views/professors/edit.html.haml
%h1 Edit Existing Professor

= form_tag professor_path(@professor), :method => :put do

  = label :professor, :name, 'Professor Name'
  = text_field :professor, 'name'

  = label :professor, :office, 'Office Location'
  = text_field :professor, 'office'
  
  = label :professor, :classes, 'Courses Taught'
  = text_field :professor, 'classes'

  = submit_tag 'Update Professor Info'
  = link_to '<button type="button">Cancel</button>'.html_safe, professors_path

app/views/professors/index.html.haml
%h1 All Professors

%table#professors
  %thead
    %tr
      %th Name
      %th Office
      %th Class
  %tbody
    - @professors.each do |professor|
      %tr
        %td= link_to(professor.name, {:action => 'show', :id => professor.id}, :class => 'action show')
        %td= professor.office
        %td= professor.classes



= link_to '<button type="button">Add New Professor</button>'.html_safe, new_professor_path
= link_to '<button type="button">Back to Dashboard</button>'.html_safe, guide_dashboard_path

app/views/professors/new.html.haml
%h1 Enter New Professor

= form_tag professors_path do

  = label :professor, :name, 'Professor Name'
  = text_field :professor, 'name'

  = label :professor, :office, 'Office Location'
  = text_field :professor, 'office'

  = label :professor, :classes, 'Courses Taught'
  = text_field :professor, 'classes'
  
  = submit_tag 'Save Changes'
  = link_to '<button type="button">Back to Professors</button>'.html_safe, professors_path

app/views/professors/show.html.haml
%h2 Details about #{@professor.name}

%ul#details
  %li
    Name:
    = @professor.name
  %li
    Office:
    = @professor.office
  %li
    Courses Taught:
    - if(!Course.where(:teacher => @professor.name).empty?)
      = link_to(@professor.classes, {:action => 'show', :id => Course.where(:teacher => @professor.name).ids , :controller=>"courses"}, :class => 'action show')
    - else
      = @professor.classes

= link_to '<button type="button">Edit</button>'.html_safe, edit_professor_path(@professor)
= button_to 'Delete', professor_path(@professor), :method => :delete, :confirm => 'Are you sure?'
= link_to '<button type="button"><< Back</button>'.html_safe, professors_path

app/views/users/index.html.haml
%h1 All Users

%table#users
  %thead
    %tr
      %th Username
      %th Password
      %th EmailID
  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.password
        %td= user.emailID

= link_to '<button type="button">Back to Dashboard</button>'.html_safe, guide_dashboard_path

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.haml
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>